spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/imagelite
    username: postgres
    password: postgres
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8081
servlet:
  multipart:
    max-file-size: 20MB
    max-request-size: 20MB